services:
- type: web
  name: lost-found-oracle
  env: node
  plan: free
  buildCommand: npm ci
  startCommand: node src/server.js
  autoDeploy: true
  envVars:
  - key: PORT
    value: 10000
  - key: ORACLE_USER
    sync: false
  - key: ORACLE_PASSWORD
    sync: false
  - key: ORACLE_CONNECT_STRING
    sync: false
  - key: ORACLE_WALLET_DIR
    value: /opt/render/project/src/wallet

